title: LOTUS SPARQL queries
description: |
  Some of LOTUS useful SPARQL queries.
queries_directory: ./queries/
query_template: ./templates/query.ejs
index_template: ./templates/index.ejs
output_directory: ./docs
