#+ summary: Natural products corresponding to given molecular formulas
#+ description: Which taxa contain structures corresponding to the following chemical formula?
#+ endpoint: https://query.wikidata.org/bigdata/namespace/wdq/sparql
#+ pagination: 100
#+ method: GET
#+ tags:
#+   - Natural products

PREFIX wdt: <http://www.wikidata.org/prop/direct/>
#title: Which taxa contain structures corresponding to the following chemical formula?
SELECT DISTINCT ?structure ?smiles_canonical ?formula ?taxon ?taxon_name WHERE {{
    VALUES ?formula {
        "C₉H₁₁Cl₂FN₂O₂S₂" # Use lower case digits ₁₂₃₄₅₆₇₈₉₀
        "C₂₂H₂₂O₉"
    }
    ?structure wdt:P274 ?formula;
    wdt:P233 ?smiles_canonical;
    wdt:P703 ?taxon.
    ?taxon wdt:P225 ?taxon_name.}
}
